name: Deploy Blazor App to Azure App Service

on:
  push:
    paths:
      - 'Ui/Http/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Ui/Http/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/moviefiles:latest

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: MovieFilesBlazor
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/moviefiles:latest
