// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MovieFiles.Infrastructure.Scaffold
{
	[Table("movie_comments", IsView = true)]
	public class MovieComment
	{
		[Column("movie_id" , SkipOnInsert = true, SkipOnUpdate = true)] public int?    MovieId  { get; set; } // integer
		[Column("comment"  , SkipOnInsert = true, SkipOnUpdate = true)] public string? Comment  { get; set; } // text
		[Column("user_name", SkipOnInsert = true, SkipOnUpdate = true)] public string? UserName { get; set; } // character varying(255)
	}
}
